apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  selector:
    app: snake-game
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
